fix: update the reamde and pre install docker if not exist.

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -36,6 +36,18 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+              sudo apt update -y
+              sudo apt install docker.io -y
+              sudo systemctl enable docker
+              sudo systemctl start docker
+              sudo usermod -aG docker $USER
+              newgrp docker
+            else
+              echo "Docker is already installed"
+            fi
+
             docker pull alfinakash/autodeploy-ec2-docker:${{ env.VERSION }}
             docker stop autodeploy || true
             docker rm autodeploy || true
